upd SDK download and extraction

diff --git a/.github/actions/download-sdk/action.yml b/.github/actions/download-sdk/action.yml
--- a/.github/actions/download-sdk/action.yml
+++ b/.github/actions/download-sdk/action.yml
@@ -14,6 +14,24 @@ runs:
       with:
         name: ${{ inputs.language }}-sdk.tar.gz
         path: ${{ github.workspace}}/sdk/
+
+    - name: Create target directory
+      shell: bash
+      run: mkdir -p ${{ github.workspace }}/sdk/${{ inputs.language }}
+
     - name: Uncompress SDK folder
       shell: bash
-      run: tar -zxf ${{ github.workspace }}/sdk/${{ inputs.language }}.tar.gz -C ${{ github.workspace }}/sdk/${{ inputs.language }}
+#      run: tar -zxf ${{ github.workspace }}/sdk/${{ inputs.language }}.tar.gz -C ${{ github.workspace }}/sdk/${{ inputs.language }}
+      run: |
+        archive_path="${{ github.workspace }}/sdk/${{ inputs.language }}-sdk.tar.gz"
+        target_dir="${{ github.workspace }}/sdk/${{ inputs.language }}"
+  
+        if [ -f "$archive_path" ]; then
+                  echo "Extracting $archive_path to $target_dir"
+                  tar -zxf "$archive_path" -C "$target_dir"
+                else
+                  echo "Error: Archive not found at $archive_path"
+                  echo "Available files in sdk directory:"
+                  ls -la ${{ github.workspace }}/sdk/
+                  exit 1
+                fi
